"""empty message

Revision ID: ca01074672ad
Revises: 
Create Date: 2021-11-26 02:52:11.521193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca01074672ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directors',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('director_full_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('director_id')
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('genre_name')
    )
    op.create_table('user_groups',
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('user_group_name', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_group_id'),
    sa.UniqueConstraint('user_group_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.user_group_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('films',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('film_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('poster', sa.Text(), nullable=False),
    sa.Column('release_date', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('added_user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['added_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('film_id')
    )
    op.create_index(op.f('ix_films_description'), 'films', ['description'], unique=False)
    op.create_index(op.f('ix_films_film_name'), 'films', ['film_name'], unique=False)
    op.create_index(op.f('ix_films_rating'), 'films', ['rating'], unique=False)
    op.create_index(op.f('ix_films_release_date'), 'films', ['release_date'], unique=False)
    op.create_table('films_directors',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('director_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['directors.director_id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.film_id'], )
    )
    op.create_table('films_genres',
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.film_id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films_genres')
    op.drop_table('films_directors')
    op.drop_index(op.f('ix_films_release_date'), table_name='films')
    op.drop_index(op.f('ix_films_rating'), table_name='films')
    op.drop_index(op.f('ix_films_film_name'), table_name='films')
    op.drop_index(op.f('ix_films_description'), table_name='films')
    op.drop_table('films')
    op.drop_table('users')
    op.drop_table('user_groups')
    op.drop_table('genres')
    op.drop_table('directors')
    # ### end Alembic commands ###
